// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.normandy.user_id", "a7d8e69e-0797-41c7-a01c-f04f4fa47009");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1697394269);
user_pref("app.update.lastUpdateTime.background-update-timer", 1697394269);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1697394269);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1697394277);
user_pref("app.update.lastUpdateTime.region-update-timer", 1697394269);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1697394696);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1697394269);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1697394360);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1697394269);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contextual-services.contextId", "{8b29bcca-1e8d-459a-97b4-5aa591a0d0b4}");
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.engagement.home-button.has-used", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1697394142);
user_pref("browser.laterrun.bookkeeping.sessionCount", 6);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 139);
user_pref("browser.newtabpage.activity-stream.impressionId", "{eff3dfb9-4ce5-4743-aab8-3ba2b08a750b}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\",\"_036a55b4-5e72-4d05-a06c-cba2dfcc134a_\"],\"idsInUrlbar\":[\"_036a55b4-5e72-4d05-a06c-cba2dfcc134a_\",\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.update.updated", 1697394244);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1697394375571");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1697396186571");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1697394319001");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1697415919001");
user_pref("browser.search.region", "TR");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20231009140911");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1697394695");
user_pref("browser.startup.couldRestoreSession.count", 2);
user_pref("browser.startup.homepage", "www.google.com");
user_pref("browser.startup.homepage_override.buildID", "20231009140911");
user_pref("browser.startup.homepage_override.mstone", "118.0.2");
user_pref("browser.startup.lastColdStartupCheck", 1697394693);
user_pref("browser.topsites.contile.lastFetch", 1697394694);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"unified-extensions-area\":[\"_036a55b4-5e72-4d05-a06c-cba2dfcc134a_-browser-action\"],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"save-to-pocket-button\",\"downloads-button\",\"fxa-toolbar-menu-button\",\"unified-extensions-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"firefox-view-button\",\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"save-to-pocket-button\",\"developer-button\",\"_036a55b4-5e72-4d05-a06c-cba2dfcc134a_-browser-action\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\",\"unified-extensions-area\"],\"currentVersion\":19,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.quicksuggest.migrationVersion", 2);
user_pref("browser.urlbar.quicksuggest.scenario", "history");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1697394250532");
user_pref("distribution.iniFile.exists.appversion", "118.0.2");
user_pref("distribution.iniFile.exists.value", false);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("doh-rollout.home-region", "TR");
user_pref("dom.push.userAgentID", "960f06ca5d604e52ad31dbc319927b98");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.getAddons.cache.lastUpdate", 1697394270);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20231009140911");
user_pref("extensions.lastAppVersion", "118.0.2");
user_pref("extensions.lastPlatformVersion", "118.0.2");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.extension.hidden", false);
user_pref("extensions.ui.lastCategory", "addons://list/extension");
user_pref("extensions.ui.locale.hidden", true);
user_pref("extensions.ui.sitepermission.hidden", true);
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.{036a55b4-5e72-4d05-a06c-cba2dfcc134a}", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"4fe91657-9701-42aa-99ee-2fc5ec5eddd2\",\"pictureinpicture@mozilla.org\":\"9538c8bb-cf10-415f-a05a-a86f77d76a23\",\"screenshots@mozilla.org\":\"8887d28e-e7cc-442a-93a4-085743ab2ceb\",\"webcompat-reporter@mozilla.org\":\"d22c2185-1f59-4884-ab61-86413d83ed78\",\"webcompat@mozilla.org\":\"8e63bd8a-fe11-4831-b309-87f05d20eb3b\",\"default-theme@mozilla.org\":\"c63d3450-f05b-4db2-a995-a1f822218cb8\",\"addons-search-detection@mozilla.com\":\"0e9bd80c-b2af-409b-a6bb-209b8bc4b0e2\",\"{036a55b4-5e72-4d05-a06c-cba2dfcc134a}\":\"2cdcf32f-204e-4eb6-a10b-10993aaae9fb\",\"google@search.mozilla.org\":\"76fa9861-5625-418e-a788-6caf0e95c0d1\",\"wikipedia@search.mozilla.org\":\"38440285-5160-49e6-8c2e-480e0fb0d41e\",\"bing@search.mozilla.org\":\"3fc7eecc-32e2-4a8f-a79f-a1ec0b834cf2\",\"ddg@search.mozilla.org\":\"19f36083-77f2-4176-a000-b9e631e632ea\"}");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("media.gmp-gmpopenh264.lastDownloadFailReason", "Error: Failed downloading via ServiceRequest, status: 0, channelStatus: null, errorCode: 5, reason: error");
user_pref("media.gmp-gmpopenh264.lastDownloadFailed", 1697394270);
user_pref("media.gmp-gmpopenh264.lastInstallStart", 1697394270);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("nimbus.syncdefaultsstore.opaqueResponseBlocking", "{\"slug\":\"opaque-response-blocking-orb-staged-release-rollout\",\"branch\":{\"slug\":\"rollout-single-branch\",\"ratio\":1,\"feature\":{\"value\":null,\"enabled\":true,\"featureId\":\"opaqueResponseBlocking\"},\"features\":null},\"active\":true,\"enrollmentId\":\"2bcd1d13-e574-42e3-afa8-a7d2878d8341\",\"experimentType\":\"rollout\",\"source\":\"rs-loader\",\"userFacingName\":\"Opaque Response Blocking (ORB) staged release rollout\",\"userFacingDescription\":\"Opaque Response Blocking (ORB) is a security hardening technology that we are rolling out gradually, while we monitor web compatibly.\",\"lastSeen\":\"2023-10-15T18:25:04.807Z\",\"featureIds\":[\"opaqueResponseBlocking\"],\"prefs\":[{\"name\":\"browser.opaqueResponseBlocking\",\"branch\":\"user\",\"featureId\":\"opaqueResponseBlocking\",\"variable\":\"enabled\",\"originalValue\":null},{\"name\":\"browser.opaqueResponseBlocking.filterFetchResponse\",\"branch\":\"user\",\"featureId\":\"opaqueResponseBlocking\",\"variable\":\"filterFetchResponse\",\"originalValue\":null},{\"name\":\"browser.opaqueResponseBlocking.javascriptValidator\",\"branch\":\"user\",\"featureId\":\"opaqueResponseBlocking\",\"variable\":\"javascriptValidator\",\"originalValue\":null},{\"name\":\"browser.opaqueResponseBlocking.mediaExceptionsStrategy\",\"branch\":\"user\",\"featureId\":\"opaqueResponseBlocking\",\"variable\":\"mediaExceptionsStrategy\",\"originalValue\":null}],\"isRollout\":true}");
user_pref("nimbus.syncdefaultsstore.opaqueResponseBlocking.enabled", true);
user_pref("nimbus.syncdefaultsstore.opaqueResponseBlocking.filterFetchResponse", 2);
user_pref("nimbus.syncdefaultsstore.opaqueResponseBlocking.javascriptValidator", true);
user_pref("nimbus.syncdefaultsstore.opaqueResponseBlocking.mediaExceptionsStrategy", 1);
user_pref("nimbus.syncdefaultsstore.upgradeDialog", "{\"slug\":\"upgrade-spotlight-rollout\",\"branch\":{\"slug\":\"treatment\",\"ratio\":1,\"feature\":{\"value\":null,\"enabled\":true,\"featureId\":\"upgradeDialog\"},\"features\":null},\"active\":true,\"enrollmentId\":\"5251d2af-baa2-443e-b8b7-c08404cd2d95\",\"experimentType\":\"rollout\",\"source\":\"rs-loader\",\"userFacingName\":\"Upgrade Spotlight Rollout\",\"userFacingDescription\":\"Experimenting on onboarding content when you upgrade Firefox.\",\"lastSeen\":\"2023-10-15T18:25:04.872Z\",\"featureIds\":[\"upgradeDialog\"],\"prefs\":[],\"isRollout\":true}");
user_pref("nimbus.syncdefaultsstore.upgradeDialog.enabled", false);
user_pref("pdfjs.enabledCache.state", false);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "4a39a333-95ab-428e-afb2-0f15fe75d1fc");
user_pref("services.settings.blocklists.addons-bloomfilters.last_check", 1697394103);
user_pref("services.settings.blocklists.gfx.last_check", 1697394103);
user_pref("services.settings.clock_skew_seconds", 166);
user_pref("services.settings.last_update_seconds", 1697394103);
user_pref("services.sync.clients.lastSync", "0");
user_pref("services.sync.declinedEngines", "");
user_pref("services.sync.globalScore", 0);
user_pref("services.sync.nextSync", 0);
user_pref("toolkit.startup.last_success", 1697394691);
user_pref("toolkit.telemetry.cachedClientID", "66097624-feb5-482d-9194-4710d6f20200");
user_pref("toolkit.telemetry.previousBuildID", "20231009140911");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
